quarkus:
  profile: ${QUARKUS_PROFILE:dev}
  application:
    name: ${QUARKUS_APP_NAME:mcorders}
  shutdown:
    timeout: 5
  banner:
    enabled: false
  http:
    port: ${QUARKUS_HTTP_PORT:8094}
  datasource:
    db-kind: ${QUARKUS_DATASOURCE_KIND:postgresql}
    jdbc:
      url: ${QUARKUS_DATASOURCE_JDBC_URL:vertx-reactive:postgresql://10.200.0.210:5432/mcorders}
    username: ${QUARKUS_DATASOURCE_USERNAME:mcorders}
    password: ${QUARKUS_DATASOURCE_PASSWORD:mcorders}
  hibernate-orm:
    database:
      generation: none
  liquibase:
    migrate-at-start: true
    change-log: "liquibase/changelog.yml"
  jaeger:
    enabled: ${QUARKUS_JEAGER_ENABLED:true}
    service-name: ${quarkus.application.name}-${quarkus.profile}
    reporter-log-spans: false
    endpoint: ${QUARKUS_JEAGER_ENDPOINT:http://10.200.0.197:14268/api/traces}
    sampler-type: const
    sampler-param: 1
  log:
    console:
      enable: true
      level: INFO
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
